/*
 * This source file was generated by the Gradle 'init' task
 */
package kanoodle.solver;

import java.util.Map;

import com.beust.jcommander.JCommander;

import kanoodle.solver.game.Level;
import kanoodle.solver.game.Piece;
import kanoodle.solver.game.solvers.Solver;
import kanoodle.solver.game.util.ParserUtil;

public class App {
    public static void main(String[] argv) throws Exception {
        Args args = new Args();
        JCommander.newBuilder().addObject(args).build().parse(argv);
        args.validate();

        Map<Character, Piece> pieces = ParserUtil.parsePieces();
        Level level = new Level(args.getConfig());
        Solver solver = args.getAlgorithm(pieces);
        System.out.println(solver.solve(level).toString(pieces, args.isNormalMode()));
    }
}
